version: '1.0.{build}'

configuration:
    - Debug

os: Visual Studio 2015

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015" ..

build_script:
    - cmake --build .
    - ctest -C %CONFIGURATION%
